### ISSUE TITLE
Weitere Endpunkte

### ISSUE THREAD

**Issue by M-Plu** [SchulIT/untisexport-service#3]
Es wäre gut, wenn man weitere Endpunkte für den Dienst konfigurieren könnte. Beispielsweise könnten die JSON in ein Verzeichnis geschrieben werden. Evtl. wäre auch ein Export in eine CSV-Datei möglich.

**Comment by frostieDE** [comment]
Export nach JSON ist möglich. Da CSV kein besonders gutes Exportformat ist, wird das nicht angeboten.
